minimum_pre_commit_version: 3.2.0
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        stages: [pre-commit, manual]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        stages: [pre-commit, manual]
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-spaces
        stages: [pre-commit, manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        stages: [pre-commit, manual]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        stages: [pre-commit, manual]
        # Same width that black uses by default.
        args: [--wrap=88, --number]
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        # Do not run with --hook-stage=manual.
        stages: [pre-commit]
        types: [python]
        language: system
        entry: venv/bin/mypy
        pass_filenames: false
